### ISSUE TITLE
SQLite-Plugin is not working in Ionic View App

### ISSUE THREAD

**Issue by venkatpolisetti** [ionic-team/ionic-view-issues#52] opened 2015-03-19 19:18 UTC
Please see the thread here: 

http://forum.ionicframework.com/t/ionic-view-app-and-sqlite-db-is-not-working/19386

Thanks

**Comment by yankustefan** [comment] 2015-03-20 08:10
#49 is maybe related

**Comment by tlancina** [comment] 2015-03-20 18:49
is this also on Android?

**Comment by venkatpolisetti** [comment] 2015-03-22 23:19
Tim,

@tlancina, I tried this only on my iphone 6. I do not have access to an Android device.

Thanks.

**Comment by rk31339** [comment] 2015-03-24 02:55
Hi,
I have a similar problem with sqlite plugin on ionic view. my app uses pre populated sqlite db and its working fine when i test on ios emulator. I see blank screen with no data populated when i test this using ionic view (for iphone 6).

**Comment by shangab** [comment] 2015-03-29 19:47
I created sql lite db like this:

var db;  //this is global 

var controllers = angular.module('starter.controllers', ['ngCordova', 'ionic.rating', 'starter.services'], function ($cordovaSQLite) {
    db = $cordovaSQLite.openDB({name: 'my.db'});
    $cordovaSQLite.exexute(db, 'CREATE TABLE IF NOT EXISTS commons (name text, value text');
    $cordovaSQLite.exexute(db, 'insert into commons (name, value) values (?,?)', ['username', 'Ali ahmed ali']);
});


Then in one of my controllers I have:

 $cordovaSQLite.execute('select name, value from commons where name=?', ['username'], function (res) {
            $scope.namename = res.item(0).value;
        });

but i get the error:

Error: [$injector:modulerr] Failed to instantiate module starter.controllers due to:
Error: [$injector:unpr] Unknown provider: $cordovaSQLite
http://errors.angularjs.org/1.3.13/$injector/unpr?p0=%24cordovaSQLite
    at REGEX_STRING_REGEXP (http://localhost:8383/adPal/www//www/lib/ionic/js/ionic.bundle.js:7988:12)
    at http://localhost:8383/adPal/www//www/lib/ionic/js/ionic.bundle.js:11922:19
    at getService (http://localhost:8383/adPal/www//www/lib/ionic/js/ionic.bundle.js:12069:39)
    at Object.invoke (http://localhost:8383/adPal/www//www/lib/ionic/js/ionic.bundle.js:12101:13)
    at runInvokeQueue (http://localhost:8383/adPal/www//www/lib/ionic/js/ionic.bundle.js:12016:35)
    at http://localhost:8383/adPal/www//www/lib/ionic/js/ionic.bundle.js:12025:11
    at forEach (http://localhost:8383/adPal/www//www/lib/ionic/js/ionic.bundle.js:8248:20)
    at loadModules (http://localhost:8383/adPal/www//www/lib/ionic/js/ionic.bundle.js:12006:5)
    at http://localhost:8383/adPal/www//www/lib/ionic/js/ionic.bundle.js:12023:40
    at forEach (http://localhost:8383/adPal/www//www/lib/ionic/js/ionic.bundle.js:8248:20)

Before all this I installed the plugin with:

cordova plugin add https://github.com/brodysoft/Cordova-SQLitePlugin.git

Any idea what is going on?

Thanks,

**Comment by venkatpolisetti** [comment] 2015-03-29 22:44
@shangab I believe, you are trying to run this in the browser. Try your app on an emulator or actual device. Cordova-SQLitePlugin is only available on the device or emulator.

**Comment by shangab** [comment] 2015-03-30 00:18
You are right. 10k thanks.

-----------------------------------------------------------------------
Apologies for the apearance,  this mail is from my tablet phone.

**Comment by kgmiller** [comment] 2015-04-01 06:08
I've also run into this issue with ngCordova / SQLite and Ionic View. I've finally gotten to the point where my brain is thinking in Angular and my app is coming together nicely in the emulator. Would be awesome to get this working with Ionic View. 

angular.module('starter', ['ionic', 'starter.controllers', 'ngCordova'])

.run(function($ionicPlatform, $cordovaSQLite) {
  $ionicPlatform.ready(function() {
    // Hide the accessory bar by default (remove this to show the accessory bar above the keyboard
    // for form inputs)
    if (window.cordova && window.cordova.plugins.Keyboard) {
      cordova.plugins.Keyboard.hideKeyboardAccessoryBar(true);
    }
    if (window.StatusBar) {
      // org.apache.cordova.statusbar required
      StatusBar.styleDefault();
    }
    window.plugins.sqlDB.copy("biases.sqlite3", function() {
      db = $cordovaSQLite.openDB("biases.sqlite3");
      initializeData($cordovaSQLite);
    }, function(error) {
          console.error("There was an error copying the database: " + error);
          db = $cordovaSQLite.openDB("biases.sqlite3");
          initializeData($cordovaSQLite);
    });
  });
})

**Comment by venkatpolisetti** [comment] 2015-04-08 19:52
@tlancina Any update on this please.

Thanks.

**Comment by arnoutaertgeerts** [comment] 2015-04-11 15:35
I'm also experiencing this issue with PouchDB.

**Comment by mnewmedia** [comment] 2015-04-22 08:35
yep really sad i can't test my app..

**Comment by tlancina** [comment] 2015-04-22 15:32
Hey guys, if you are trying to execute the SQLite plugin within `ionic.Platform.ready` it will most likely fail because `ionic.Platform.ready` fires immediately, but the plugin hasn't initialized yet.  Try wrapping the code in a $timeout instead of `ionic.Platform.ready`.

This is an annoying gotcha that will be addressed in a future release.

**Comment by mnewmedia** [comment] 2015-04-24 10:31
but i don't execute the plugin by myself, pouchdb does everything for me? so does somebody also know a workaround for pouchdb?

**Comment by ryandraper** [comment] 2015-05-05 18:31
Adding the $timeout of 3 seconds before initializing my database worked for me:)  Also wrap all calls to $cordovaSQLite.... in "if(window.sqliteplugin){do your stuff}".  Thanks @tlancina

**Comment by tlancina** [comment] 2015-05-05 22:30
@ryandraper wow that is way longer than I ever experienced! I've had a chance to actually look into some of the major View issues and the whole deviceready thing is actually caused by isWebView in Ionic returning false because Cordova hasn't loaded yet.

So if you guys aren't adverse to a small hack, adding `<script>window.phonegap = {}</script>` to your <head> before Ionic loads should force it to wait for the deviceready event without stepping on Cordova's toes once it does load. Much simpler than writing $timeout everywhere.

**Comment by ryandraper** [comment] 2015-05-14 06:17
Just saw the reply today @tlancina :).  Yes, for sure it doesn't take that long to become ready, in fact it's probably a small fraction of a second.

I just put in something like this as a backup before calling the database:

var startMs = (new Date).getTime();
      while(!window.sqlitePlugin){
        console.log('waiting');
        var currentMs = (new Date).getTime();
        if( (currentMs - startMs) > 3000){
          alert('timed out waiting for database');
          break;
        }
      }
after the while loop do your code

Not sure if this is the most efficient but while running the ios emulator I didn't even see one console.log show up which tells me it only takes a fraction of a second to be ready.  I did put a 750ms timeout on my hide spinner code so it looks like the app is 'loading up' :)

**Comment by bittusinghmca** [comment] 2015-06-17 06:47
I am unable to install cordova plugin in my ionic project
its showing me this error. "cross-device link not permitted"

cordova plugin add https://github.com/litehelpers/Cordova-sqlite-storage.git

Whats the problem any help will be really appreciable .

Thanks in advance

**Comment by bhoopaljanga** [comment] 2015-07-31 13:34
same issue her also unable to install
internal error. "cross-device link not permitted"
i am using cordvoa 5.1.1
thanks in advance

**Comment by fwcontact** [comment] 2015-09-13 20:33
The following piece worked for me. 

    function activate() {
      if (window.cordova) { 
        // listen on "document" (according to official SQLite Plugin API doc)
        document.addEventListener("deviceready", doReady, false);
      } else { 
        // listen on ionic
        $ionicPlatform.ready(doReady);
      }

      function doReady() {
        // setup local persistence
        setupLocalPersistence();
        // setup remote resources
        setupRemoteResources();
      }
    }

**Comment by jpike88** [comment] 2015-10-14 05:53
@fwcontact Could you post your code in setupLocalPersistence? That code snippet you provided isn't enough to know what's going on.

**Comment by fwcontact** [comment] 2015-10-14 06:05
@jpike88 ,
After I posted my last comment, I made some changes in my code.
Now I've pulled out the persistence logic into a service (factory).
Below is the full piece of the file "shell.service.local-database".
----------------------------

(function () {
  'use strict';

  angular.module('app.shell')
    .factory('localDatabaseService', localDatabaseService);

  localDatabaseService.$inject =
    ['$ionicPlatform',
      '$cordovaSQLite',
      '$window',
      'shellConstants'];

  function localDatabaseService
  ($ionicPlatform,
   $cordovaSQLite,
   $window,
   shellConstants) {

    //
    // fields
    //

    var _db = '';


    //
    // singleton
    //

    return {
      getDatabase: getDatabase
    };


    //
    // methods
    //

    function getDatabase() {
      // promise
      return $ionicPlatform.ready(
        function () {
          // lazy init
          if (!_db) {
            if ($window.cordova) {
              // native
              _db = $cordovaSQLite.openDB(shellConstants.DATABASE_NAME);
              console.log('native db', _db);
            } else {
              // web
              _db = $window.openDatabase(
                shellConstants.DATABASE_NAME,
                '1.0',
                shellConstants.DATABASE_NAME,
                1000 * 1000 * 10);
              console.log('web db', _db);
            }
          }
        })
        .then(function () {
          // for chaining use
          return _db;
        });
    }
  }

})();

**Comment by fwcontact** [comment] 2015-10-14 06:09
@jpike88 ,

(function () {
  'use strict';

  angular.module('app.shell')
    .factory('localDatabaseService', localDatabaseService);

  localDatabaseService.$inject =
    ['$ionicPlatform',
      '$cordovaSQLite',
      '$window',
      'shellConstants'];

  function localDatabaseService
  ($ionicPlatform,
   $cordovaSQLite,
   $window,
   shellConstants) {

    //
    // fields
    //

    var _db = '';


    //
    // singleton
    //

    return {
      getDatabase: getDatabase
    };


    //
    // methods
    //

    function getDatabase() {
      // promise
      return $ionicPlatform.ready(
        function () {
          // lazy init
          if (!_db) {
            if ($window.cordova) {
              // native
              _db = $cordovaSQLite.openDB(shellConstants.DATABASE_NAME);
              console.log('native db', _db);
            } else {
              // web
              _db = $window.openDatabase(
                shellConstants.DATABASE_NAME,
                '1.0',
                shellConstants.DATABASE_NAME,
                1000 * 1000 * 10);
              console.log('web db', _db);
            }
          }
        })
        .then(function () {
          // for chaining use
          return _db;
        });
    }
  }

})();

**Comment by jpike88** [comment] 2015-10-14 06:14
Champion

**Comment by fwcontact** [comment] 2015-10-14 06:21
Hi @jpike88 , I've updated my environment to Ionic (1.6.5) and  Cordova (5.3.3). And I'm now only using $ionicPlatform for the call back, and it just works. The reason I checks on "$window.cordova" is because I wanted to use the web sql database/standard, when I'm developing on a desktop (with Safari), and not launching the emulator so frequently. That saved me much time. I also brought in "cordova-sqlite-storage" plugin, it works for native sqlite and web database/standard. The only thing we have to diverse by ourselves is to get a database instance/reference. After that, we can just feed the database to "$cordovaSQLite"'s "execute" method. That's my understanding for now. And I'm still monitoring the results.

**Comment by PrithvirajChauhan** [comment] 2015-10-15 06:23
In my code $cordovaSQLite.execute function works good in .run function but gives me error in my controller . I don't know what i am doing wrong , i have included all the required plugin and follow step of this very good example https://blog.nraboy.com/2014/11/use-sqlite-instead-local-storage-ionic-framework/

 var db = null;
    var myapp=angular.module('starter', ['ionic','btford.socket-io','LoginCntrl','SlideCntrl','app','ChatCntrl','ngCordova','ngCordova.plugins.sqlite'])

.run(function($ionicPlatform,$cordovaSQLite) {
    $ionicPlatform.ready(function() {

        // Hide the accessory bar by default (remove this to show the accessory bar above the keyboard
        // for form inputs)
        if(window.cordova && window.cordova.plugins.Keyboard) {
            cordova.plugins.Keyboard.hideKeyboardAccessoryBar(true);
        }
        if(window.StatusBar) {
            StatusBar.styleDefault();
        }
        console.log("The application is resuming from the background");
        db = $cordovaSQLite.openDB({ name: App_DB_Name });
        $cordovaSQLite.execute(db, "CREATE TABLE IF NOT EXISTS people (id integer primary key, firstname text, lastname text)");

        var query = "SELECT firstname, lastname FROM people WHERE lastname = ?";
        $cordovaSQLite.execute(db, query, ["pruthvi"]).then(function(result) {
            if(result.rows.length > 0) {
                console.log("SELECTED -> " + result.rows.item(0).firstname + " " + result.rows.item(0).lastname);
                alert("SELECTED -> "+ result.rows.item(0).firstname + " " + result.rows.item(0).lastname)
            } else {
                console.log("No results found");
            }
        }, function (err) {
            console.error(err);
        });
        //  $cordovaSQLite.execute(db, "CREATE TABLE IF NOT EXISTS "+ App_DB_Table_Login_Name +"(id integer primary key, login_username text, login_password text)");
        console.log("success");
    });
});


myapp.controller('IndexController', ['$scope','$rootScope', function($scope,$rootScope,$cordovaSQLite, $ionicPlatform){
    var query = "SELECT firstname, lastname FROM people WHERE lastname = ?";
    $cordovaSQLite.execute(db, query, ["pruthvi"]).then(function(result) {
        if(result.rows.length > 0) {
            console.log("SELECTED -> " + result.rows.item(0).firstname + " " + result.rows.item(0).lastname);
            alert("SELECTED -> "+ result.rows.item(0).firstname + " " + result.rows.item(0).lastname)
        } else {
            console.log("No results found");
        }
    }, function (err) {
        console.error(err);
    });
}]);

**Comment by fwcontact** [comment] 2015-10-15 10:34
Hi @PrithvirajChauhan ,
I noticed that in your controller, you didn't wrap the $cordovaSQLite call with a "$ionicPlatform.ready()" callback. 
You should always wrap the $cordovaSQLite call in a "ready" call back. 
And it's not just for $cordovaSQLite, pretty much every plugin covered in ngCordova requires this procedure.
So for the exception, I think it's because your controller get instantiated too soon.

**Comment by fpassa** [comment] 2016-08-23 19:41
I've personally found this App Template well explanatory on how to use SQLite in Ionic with pre-populate database as well. Check it out here: https://codecanyon.net/item/quizionic-a-quiz-app-template-for-ionic-framework-with-sqlite-database/14205904

**Comment by n1t1nv3rma** [comment] 2017-01-16 11:35
Hello Mates,

It is strange! But "if (this.platform.is('**Cordova**')) solved all my issues with the Ionic View. Notice that "C" is capital in Cordova! It took me several hit and trials to find this out!

Hope it helps! :)

**Comment by tlancina** [comment] 2017-09-22 14:23
Hey thanks for the issue! With Ionic Pro we’re consolidating our support, so please head over to http://support.ionicjs.com if you’re having problems, thanks!

**Closed by tlancina** 2017-09-22 14:23 UTC
